### PR TITLE
fix(validation): RFC-5322 compliant email validation

### PR DESCRIPTION
**Pull request by nfoucha**
The current email validation is insufficient as it will fail with commonly occurring patterns (john+doe@example.com).  This PR adds a more robust regex which more closely aligns with the RFC-5322 standard.

### CODE REVIEW

**Comment by boywithkeyboard** [comment]
@nfoucha thank you for letting me know about this issue!

What do you think of this Regex?
https://github.com/colinhacks/zod/blob/master/src/types.ts#L560

**Comment by nfoucha** [comment]
Looks good to me, want me to update the PR to use it, or close the PR and let you drive?  I'm not at my desk at the moment so it'll be a bit before I can get to it.

**Comment by boywithkeyboard** [comment]
@nfoucha sure, go ahead! I'll merge it tomorrow!

**Comment by nfoucha** [comment]
@boywithkeyboard Done

**Pull request merged**
